### ISSUE TITLE
follow_path: loitering option

### ISSUE THREAD

**Issue by ukos-git** [PokemonGoF/PokemonGo-Bot-Backup#23]
repost of the lost issue https://github.com/PokemonGoF/PokemonGo-Bot/issues/5416

brief summary: 
There is a misunderstanding of the use of the loitering functionality.
@alexyaoyang, myself and the original author of the loitering option wanted to use it to let the bot handle other running tasks. [current master](https://github.com/PokemonGoF/PokemonGo-Bot/blob/11123a82cb18c172a262dc9e46e7b2c175666828/pokemongo_bot/cell_workers/follow_path.py#L144) has this functionality. It is also explained in the docs.

In [dev](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/follow_path.py#L144) the loitering was changed to really do nothing at all besides catching pokemon etc. so the running task was held further active. 

The newly changed behaviour should also be the case if no running task at all is added after the loitering. Therfore I would like to revert the old loitering behaviour if @Anakin5 agrees who's to blame.

Any thoughts maybe from @janpascal

**Comment by alexyaoyang** [comment]
Thanks for bring this back @ukos-git. I've yet to look through the issues that @Anakin5 was trying to solve when he changed the loiter feature, seems like it might not be possible now.

I agree that the loiter feature should allow bot to walk if users chooses, but let's not blame @Anakin5 for thinking that loiter doesn't move, since the word `loiter` does have both meanings of waiting still and walking around. 

I suggest we add the old loiter back, and at the same time improve on our docs to tell users clearly that the bot will behave differently based on what task arrangement they have.

**Comment by janpascal** [comment]
Agreed. Maybe the term loitering is to blame, I'm not native in English so it may have connotations I didn't expect. 

By the way, in master loitering with a polylinewalker doesn't work properly, I'm trying to find out what's wrong.

**Comment by ukos-git** [comment]
I was just using the term blame because of the git blame command which is btw one nice feature. No offense.
For me it was the first time using the bot so I really think, that improving the docs at that point would help. 
I am also not native english and had to look the term up as I never heard of it. Maybe  don't use "loiter" at all. "wander" would be a more clear word to me.

**Comment by janpascal** [comment]
+1 for changing the name to 'wander'.

**Comment by julienlavergne** [comment]
It is ok for me as well. We just have to return Success instead of running.
